### ISSUE TITLE
Minimized app isn't displayed with window.show()

### ISSUE THREAD

**Issue by jouni-kantola** [neutralinojs/neutralinojs#1232]
**Describe the bug**

The `Neutralino.window.show()` doesn't show the app when it's minimized in Windows 11.

With the following example code, the window should be displayed after 3 seconds, but it's not.

```javascript
async function minimizeAndShow3SecondsLater() {
  await Neutralino.window.minimize();
  setTimeout(async () => {
      await Neutralino.window.show(); // doesn't work; should restore to width/height before minimizing
      // await Neutralino.window.maximize(); // works
  }, 3000);
}
```

**To Reproduce**

1. Download the following repro: [neutralinojs-show-minimized-bug-repro.zip](https://github.com/neutralinojs/neutralinojs/files/14843842/neutralinojs-show-minimized-bug-repro.zip)
2. Unzip
3. cd `.\neutralinojs-show-minimized-bug-repro`
4. `npx @neutralinojs/neu update`
5. `npx @neutralinojs/neu run`
6. Press button _Minimize and show in 3 seconds_
7. App stays minimized 😞 

**Expected behavior**

In step 7, app window should be displayed after 3 seconds.

**Specifications**

Operating system:
```
OS Name             : Microsoft Windows 11 Business
OS Version          : 10.0.22631
```

`npx @neutralinojs/neu version`:
```
--- Global ---
neu CLI: v9.6.0

--- Project: bug-repro (js.neutralino.sample) ---
Neutralinojs binaries: v5.1.0
Neutralinojs client: v5.1.0
Project version: v1.0.0
```

**Comment by shalithasuranga** [comment]
This issue was fixed via #1235 and the changes will be released with the next version (But, you all can test this feature with  tommorrow's nightly build). Thanks :tada:

**Comment by jouni-kantola** [comment]
@shalithasuranga and/or @moataz2002: I used the [repro in the OP](https://github.com/neutralinojs/neutralinojs/files/14843842/neutralinojs-show-minimized-bug-repro.zip) with version updated to `nightly`. Unfortunately, the app window still doesn't appear with `show()` when minimized. I'm on Windows 11, if that makes any difference to the environment you're comparing with. Could you, please, also test the repro with the nightly build? Thank you in advance!

```
npx @neutralinojs/neu version

[...]

--- Global ---
neu CLI: v9.6.0

--- Project: bug-repro (js.neutralino.sample) ---
Neutralinojs binaries: nightly
Neutralinojs client: nightly
Project version: v1.0.0
```

**Comment by jouni-kantola** [comment]
@shalithasuranga I tried the bug repro with `v5.2.0` in Windows 11 and the app still doesn't automatically appear on `show()` when minimized.

```sh
npx @neutralinojs/neu version

[...]

--- Global ---
neu CLI: v9.6.0

--- Project: bug-repro (js.neutralino.sample) ---
Neutralinojs binaries: v5.2.0
Neutralinojs client: v5.2.0
Project version: v1.0.0
```

**Comment by shalithasuranga** [comment]
Hello @jouni-kantola, thanks so much for checking this issue again with the latest version. Let's re-open this issue since it's not resolved correctly :tada:

**Comment by jouni-kantola** [comment]
As of v5.4.0, `window.show()` still doesn't display a minimized window in Windows. However, using `window.unminimize()` does:
```async function minimizeAndShow3SecondsLater() {
  await Neutralino.window.minimize();
  setTimeout(async () => {
    console.log("3 seconds later", await Neutralino.window.isMinimized());
    if (await Neutralino.window.isMinimized()) {
      await Neutralino.window.unminimize();
    }
  }, 3000);
}
```

@shalithasuranga Up to you, if you want to close the issue, now that there is a workaround.

**Comment by shalithasuranga** [comment]
Closing this since a workaround is posted. Thanks so much :tada:
