### ISSUE TITLE
v4.1.0 - Native API broken using chrome mode

### ISSUE THREAD

**Issue by Blatman** [neutralinojs/neutralinojs#751]
NS: 4.1.0
CL: 3.0.0+
OS: Mac 10.13.6

Native API doesn't appear to work with chrome mode.

When main app window is closed via close button the window closes but the app icon remains in dock, looking at the Activity Monitor shows the processes still running (app process and Google processes) - the app In this case uses neutralino.app.exit() via main.js code but not sure if the exitProcessOnClose feature is implemented for Chrome mode.

Using the rest of the Native API does nothing not even returning errors -

eg: 
var value = Neutralino.os.getEnv('USER')
.then(function(value) {
    console.log('USER = ', value);
})
.catch(function(err) {
    console.log('errGetEnvUSER', err);
});

Nothing returned.

        var trayo = Neutralino.os.setTray(tray)
//        .then(function(trayo) {
//console.log('BINGO', trayo);
//        })
        .catch(function(err) {
            console.log('errSetTray', err);
        })

Tray not started - no err returned

GOOD news - HTML media tags work perfectly ....

**Comment by shalithasuranga** [comment]
Hey.. Thanks for checking. chrome mode is basically running Chrome instance with some CLI args to make it look more like a native app. We use a C++ rewrite of https://github.com/zserge/lorca's concept. It's like the browser mode, so we cannot control the window. But not sure about the tray menu - need to check a bit. get.Env related issue was fixed now :)

**Comment by Blatman** [comment]
@shalithasuranga  - Still trying to get the Native API going but major concern is the closing of the app. If the app is quit from the dock icon the Google processes close but the app process remains (although the actual main window has closed). The app process needs a force-quit to close but if the app is relaunched when the process is still present the machine needs to be shutdown by holding the power switch off.

**Comment by shalithasuranga** [comment]
Hey.. native API worked fine for me when I check with v4.1.0.. Did you check with the release version? Mm.. looks like we need to terminate the chrome process. Looks like macOS process behavior is different. On Linux, the app session goes away whenever we click on the close button. I will check about the app closing issue on Mac

**Comment by Blatman** [comment]
@shalithasuranga - aye tried v4.1.0 just before asio added, using console.log I get some returns but some parts still not working -
eg: using the os.showMessageBox I get data returned but the dialog does not show - is this keyed to the window mode?

L323 document.getElementById('listGV').onclick = async function listGV(){
L324
L325     var title = 'Global Variables (default)',
L326           content = 'Defaults -  (inbuilt)\nNL_OS (OS): ' + NL_OS + '\n' + 'NL_APPID: ' + NL_APPID + '\n' +'NL_PORT: ' + NL_PORT + '\n' +'NL_MODE: ' + NL_MODE + '\n' +'NL_VERSION (Server): ' + NL_VERSION + '\n' +'NL_CVERSION (Client): ' + NL_CVERSION + '\n' +'NL_CWD: ' + NL_CWD + '\n' +'NL_PATH (App root): ' + NL_PATH + '\n' +'NL_ARGS: ' + NL_ARGS + '\n' +'NL_PID: ' + NL_PID + '\n' +'NL_TOKEN: ' + NL_TOKEN + '\n' +'NL_APPVERSION: ' + NL_APPVERSION + '\n\nCustom -  (defined in neutralino.config.json file)\n' +'NL_TESTPATH: ' + NL_TESTPATH + '\n' +'NL_BINROOT (Binary root): ' + NL_BINROOT;
L327  console.log(Date.now() + ' - preShowMessageBox --> Defaults -  (inbuilt)\nNL_OS (OS): ' + NL_OS + '\n' + 'NL_APPID: ' + NL_APPID + '\n' +'NL_PORT: ' + NL_PORT + '\n' +'NL_MODE: ' + NL_MODE + '\n' +'NL_VERSION (Server): ' + NL_VERSION + '\n' +'NL_CVERSION (Client): ' + NL_CVERSION + '\n' +'NL_CWD: ' + NL_CWD + '\n' +'NL_PATH (App root): ' + NL_PATH + '\n' +'NL_ARGS: ' + NL_ARGS + '\n' +'NL_PID: ' + NL_PID + '\n' +'NL_TOKEN: ' + NL_TOKEN + '\n' +'NL_APPVERSION: ' + NL_APPVERSION + '\n\nCustom -  (defined in neutralino.config.json file)\n' +'NL_TESTPATH: ' + NL_TESTPATH + '\n' +'NL_BINROOT (Binary root): ' + NL_BINROOT);
L328
L329    Neutralino.os.showMessageBox(title, content); 
}


L329 does not work L327 logs OK in inspector.

Also finding that using the API after the main window clientconnect event may be important in this mode.
